---
version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "4000:4000"
        environment:
            - DATABASE_URL=postgres://dbuser:dbpass@db:5432/dbname
            - MIX_ENV=test
        depends_on:
            - db

    db:
        image: postgres:11.3-alpine
        restart: always
        ports:
            - "15432:5432"
        # volumes:
        #   - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_DB=dbname
            - POSTGRES_PASSWORD=dbpass